armour/company/urls.py
from django.conf.urls import url
from .views import CCUpdateView, CCConfirmView, CCSuccessView, OrganizationUpdate, EmployeeAddView, EmployeeListView, \
    EmployeeEditView, EmployeeDeleteView, OrganizationAdmins, OrganizationAdminsListView, OrganizationAdminsAddView, \
    OrganizationAdminsEditView, OrganizationAdminsDeleteView, CompanyUpdate, LegalUpdate, SubscriptionView, \
    PaymentsListView, CancelSubscriptionView, CompanyBuilderStep1View, CompanyBuilderStep1UpdateView, CompanyBuilderStep2UpdateView, CompanyBuilderStep3UpdateView, CompanyBuilderStep4UpdateView,CompanyBuilderConfirmationView, StartFreeView

urlpatterns = [
    url(r'^credit-cart/update/$', CCUpdateView.as_view(), {}, 'cc-update'),
    url(r'^credit-cart/confirm/$', CCConfirmView.as_view(), {}, 'cc-confirm'),
    url(r'^credit-cart/success/(?P<uuid>[\w\-]+)/$', CCSuccessView.as_view(), {}, 'cc-success'),
    url(r'^organization/update/$', OrganizationUpdate.as_view(), {}, 'organization-update'),
    url(r'^employee/add/$', EmployeeAddView.as_view(), {}, 'employee-add'),
    url(r'^employee/list/$', EmployeeListView.as_view(), {}, 'employee-list'),
    url(r'^employee/edit/(?P<pk>\d+)/$', EmployeeEditView.as_view(), {}, 'employee-edit'),
    url(r'^employee/delete/(?P<pk>\d+)/$', EmployeeDeleteView.as_view(), {}, 'employee-delete'),
    url(r'^organization/admins/$', OrganizationAdmins.as_view(), {}, 'organization-admins'),
    url(r'^organization/admins/list/$', OrganizationAdminsListView.as_view(), {}, 'organization-admins-list'),
    url(r'^organization/admins/add/$', OrganizationAdminsAddView.as_view(), {}, 'organization-admins-add'),
    url(r'^organization/admins/edit/(?P<pk>\d+)/$', OrganizationAdminsEditView.as_view(), {},
        'organization-admins-edit'),
    url(r'^organization/admins/delete/(?P<pk>\d+)/$', OrganizationAdminsDeleteView.as_view(), {},
        'organization-admins-delete'),
    url(r'^profile/update/$', CompanyUpdate.as_view(), {}, 'profile-update'),
    url(r'^profile/legal-information/$', LegalUpdate.as_view(), {}, 'legal-info'),
    url(r'^subscription/$', SubscriptionView.as_view(), {}, 'subscription'),
    url(r'^subscription/list/$', PaymentsListView.as_view(), {}, 'subscription-list'),
    url(r'^subscription/cancel/$', CancelSubscriptionView.as_view(), {}, 'subscription-cancel'),
    url(r'^organization/builder/step/1/$', CompanyBuilderStep1View.as_view(), {}, 'organization-step-1'),
    url(r'^organization/builder/step/1/update/$', CompanyBuilderStep1UpdateView.as_view(), {},
        'organization-step-1-update'),
    url(r'^organization/builder/step/2/update/$', CompanyBuilderStep2UpdateView.as_view(), {},
        'organization-step-2-update'),
    url(r'^organization/builder/step/3/update/$', CompanyBuilderStep3UpdateView.as_view(), {},
        'organization-step-3-update'),
    url(r'^organization/builder/step/4/update/$', CompanyBuilderStep4UpdateView.as_view(), {},
        'organization-step-4-update'),
    url(r'^organization/builder/step/confirmation/$', CompanyBuilderConfirmationView.as_view(), {},
        'organization-step-confirmation'),
    url(r'^organization/start/free/trial/$', StartFreeView.as_view(), {},
        'organization-start-free'),

]

armour/general/urls.py
from django.urls import path

from .views import ContactView, PaneView, TMPView, TipsListView, TipDetailView, home_redirect

urlpatterns = [
    path('', home_redirect, name='home'),
    path('panel/', PaneView.as_view(), name='panel'),
    path('forms/contact/', ContactView.as_view(), name='contact-form'),
    path('templates/', TMPView.as_view(), name='tmp'),
    path('tips/', TipsListView.as_view(), name='tips-list'),
    path('tips/<int:pk>/', TipDetailView.as_view(), name='tip-details'),
]

armour/user/urls.py
from django.conf.urls import url
from .views import ArmourLoginView, ArmourLogoutView, PasswordChangeView, RegisterView, AskLogoutView, ResetPassView, \
    ResetPassInfoView, ResetPassConfirmView, ResetPassConfirmInfoView, AcivateAccountView, ConfirmInfoView
from django.conf import settings

urlpatterns = [
    url(r'^login/$', ArmourLoginView.as_view(), {}, 'login'),
    url(r'^logout/$', ArmourLogoutView.as_view(), {}, 'logout'),
    url(r'^logout/confirmation/$', AskLogoutView.as_view(), {}, 'logout-ask'),
    url(r'^password/change/$', PasswordChangeView.as_view(), {}, 'change-password'),
    url(r'^password/reset/$', ResetPassView.as_view(), {}, 'reset-password'),
    url(r'^password/reset/info/$', ResetPassInfoView.as_view(), {}, 'reset-password-info'),
    url(r'^password/reset/change/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        ResetPassConfirmView.as_view(), {}, 'reset-password-change'),
    url(r'^password/reset/confirm/$', ResetPassConfirmInfoView.as_view(), {}, 'reset-password-confirm'),
    url(r'^activate/(?P<uuid>[0-9A-Fa-f-]+)/$', AcivateAccountView.as_view(), {}, 'activate-account'),
    url(r'^activate/email/confirmation/$', ConfirmInfoView.as_view(), {}, 'activate-email-conf'),
]

if settings.REGISTARTION_VIEW:
    urlpatterns.append(url(r'^register/$', RegisterView.as_view(), {}, 'register'), )

config/urls.py
from django.conf import settings
from django.conf.urls import  url
from django.urls import include, path
from django.contrib import admin
from django.views import defaults as default_views
from armour.general.views import PrivateDocView
urlpatterns = [
    path('admin/', admin.site.urls),
    path("admin/", include('loginas.urls')),
    path('', include('armour.general.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('account/', include('armour.user.urls')),
    path('company/', include('armour.company.urls')),
    path('legislation/', include('armour.legislation.urls')),
    path('media/<path:path>/', PrivateDocView.as_view(), name='get-media'),
]

if settings.DEBUG:
    #from django.conf.urls.static import static
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
                          url(r'^__debug__/', include(debug_toolbar.urls)),
                      ] + urlpatterns


admin.sites.AdminSite.site_header = 'Operationarmour Admin Panel'
admin.sites.AdminSite.site_title = 'Operationarmour Admin Panel'
admin.sites.AdminSite.index_title = 'Operationarmour'

armour/legislation/models.py
import os
import re
import uuid
from datetime import timedelta

from ckeditor.fields import RichTextField
from django.conf import settings
from django.contrib.sites.models import Site
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.query_utils import Q
from django.utils.html import strip_tags
from django.utils.translation import ugettext_lazy as _
from djchoices import ChoiceItem, DjangoChoices


class Location(models.Model):
    name = models.CharField(_('Name'), max_length=120)
    published = models.BooleanField(_('Published'), default=True)
    vat = models.ForeignKey("VATRate", null=True, on_delete=models.CASCADE, blank=True, )
    ord = models.IntegerField(_('Order'), default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _(u'Location')
        verbose_name_plural = _(u'Locations')
        ordering = ['ord']


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=120)
    published = models.BooleanField(_('Published'), default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _(u'Sector')
        verbose_name_plural = _(u'Sectors')


class Topic(models.Model):
    name = models.CharField(_('Name'), max_length=120)
    published = models.BooleanField(_('Published'), default=True)
    ord = models.IntegerField(_('Order'), default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _(u'Topic')
        verbose_name_plural = _(u'Topics')
        ordering = ['ord']


class PriceSettings(models.Model):
    site = models.OneToOneField(Site, related_name="site_settings", on_delete=models.CASCADE)
    disc_choice = models.BooleanField(_('Discont on two or more choices'), default=False)
    disc_topic = models.PositiveIntegerField("Discount Topic", null=False, default=0,
                                             validators=[MinValueValidator(0), MaxValueValidator(100)])
    disc_location = models.PositiveIntegerField("Discount Location", null=False, default=0,
                                                validators=[MinValueValidator(0), MaxValueValidator(100)])
    disc_next_choice = models.BooleanField(_('Discont on every next choice'), default=False)
    disc_next_topic = models.PositiveIntegerField("Discount Next Topic", null=False, default=0,
                                                  validators=[MinValueValidator(0), MaxValueValidator(100)])
    disc_next_location = models.PositiveIntegerField("Discount Next Location", null=False, default=0,
                                                     validators=[MinValueValidator(0), MaxValueValidator(100)])

    def __str__(self):
        return self.site.name

    class Meta:
        verbose_name = _(u'Price Settings')
        verbose_name_plural = _(u'Price Settings')


class VATRate(models.Model):
    settings = models.ForeignKey(PriceSettings, on_delete=models.CASCADE, related_name="vat")
    name = models.CharField(_('Name'), max_length=400, unique=True)
    value = models.PositiveIntegerField(_('Value'), validators=[MinValueValidator(1), MaxValueValidator(99), ])
    stripeId = models.CharField(_('Stripe'), max_length=400, null=True, blank=True, editable=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _(u'VAT Rate')
        verbose_name_plural = _(u'VAT Rates')
        ordering = ['name']


class Currency(models.Model):
    name = models.CharField(_('Code'), max_length=4, primary_key=True)
    settings = models.ForeignKey(PriceSettings, null=True, on_delete=models.CASCADE, blank=False,
                                 related_name="currency")
    main = models.BooleanField(_('Default'), default=False, )
    published = models.BooleanField(_('Published'), default=True),

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _(u'Currency')
        verbose_name_plural = _(u'Currencys')


class DiscountCodes(models.Model):
    name = models.CharField(_('Description'), max_length=250, )
    settings = models.ForeignKey(PriceSettings, null=True, on_delete=models.CASCADE, blank=False, related_name="dcodes")
    size = models.PositiveIntegerField("Size [%]", null=False, default=1,
                                       validators=[MinValueValidator(1), MaxValueValidator(100)])
    code = models.CharField(_('Code'), max_length=10, unique=True)

    multiple = models.BooleanField(_('Multiple-use'), default=False)
    used = models.BooleanField(_('Used'), default=False, editable=False)
    active = models.BooleanField(_('Active'), default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _(u'Discount Code')
        verbose_name_plural = _(u'Discount Codes')


class LegislationTopic(models.Model):
    title = models.CharField(_('Title'), max_length=300)
    description = RichTextField(_('Full description'), max_length=60000, null=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name="leglocations")
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="legtopics")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    published = models.BooleanField(_('Published'), default=True)
    version = models.PositiveIntegerField(_('Version'), default=1)

    changed = models.BooleanField(_('Changed'), default=False, editable=False)

    free = models.BooleanField(_('Show for free'), default=False, )
    order = models.PositiveIntegerField(_('Order for free'), default=1)
    orderfull = models.PositiveIntegerField(_('Order for full'), default=1)

    def get_keyp(self):
        return self.kpoints.filter(published=True).distinct().order_by('id')

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):
    #     if self.pk:
    #         old = LegislationTopic.objects.get(id=self.pk)  # fetch current data from db to examine version
    #         if old.version < self.version:  # changing version
    #
    #             for question in self.legquestions.all():
    #                 copy = Question.objects.get(id=question.id)
    #                 copy.pk = None
    #                 copy.legtopic = self
    #                 copy.parent = question
    #                 copy.changed = False
    #                 copy.save()
    #
    #             for point in self.kpoints.all():
    #                 copy = KeyPoint.objects.get(id=point.id)
    #                 copy.pk = None
    #                 copy.legtopic = self
    #                 copy.parent = point
    #                 copy.changed = False
    #                 copy.save()
    #
    #                 for comply in point.topcomply.all():
    #                     comply_copy = LegislationTopicComply.objects.get(id=comply.id)
    #                     comply_copy.pk = None
    #                     comply_copy.point = copy
    #                     comply_copy.save()
    #
    #     super(LegislationTopic, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _(u'Legislation topic')
        verbose_name_plural = _(u'Legislation topics')
        ordering = ['title']


class Question(models.Model):
    title = models.TextField(_('Title'), max_length=2000)
    published = models.BooleanField(_('Published'), default=True)
    legtopic = models.ForeignKey(LegislationTopic, on_delete=models.CASCADE, related_name="legquestions", null=True, )
    changed = models.BooleanField(_('Changed'), default=False, editable=False)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, related_name="questionchilds", null=True, blank=True,
                               editable=False)
    desc = models.TextField(_('Description'), max_length=6000, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _(u'Question')
        verbose_name_plural = _(u'Questions')


class Requirements(models.Model):
    name = models.CharField(_('Name'), max_length=600)
    description = RichTextField(_('Full description'), max_length=60000, null=True)
    nodescription = models.TextField(_('Non Conformance description'), max_length=2000, null=True, blank=True)
    published = models.BooleanField(_('Published'), default=True)

    def __str__(self):
        return self.name

    def points_active(self):
        return self.reqpoints.filter(published=True).distinct().order_by('id')

    class Meta:
        verbose_name = _(u'Standard or Other Requirement')
        verbose_name_plural = _(u'Standard or Other Requirements')


class KeyPoint(models.Model):
    point = RichTextField(_('Key Point'), max_length=60000, )
    published = models.BooleanField(_('Published'), default=True)
    legtopic = models.ForeignKey(LegislationTopic, on_delete=models.CASCADE, related_name="kpoints", null=True, )
    req = models.ForeignKey(Requirements, on_delete=models.CASCADE, related_name="reqpoints", null=True, )
    changed = models.BooleanField(_('Changed'), default=False, editable=False)
    parent = models.ForeignKey("self", on_delete=models.CASCADE, related_name="kpchilds", null=True, blank=True,
                               editable=False)

    def __str__(self):
        try:
            return re.compile('<strong>(.*?)</strong>', re.DOTALL | re.IGNORECASE).findall(self.point)[0]
        except:
            return strip_tags(self.point)

    class Meta:
        verbose_name = _(u'Key Point')
        verbose_name_plural = _(u'Key Points')
        ordering = ['id']


class LegislationTopicComply(models.Model):
    title = RichTextField(_('Title'), max_length=60000, )
    point = models.ForeignKey(KeyPoint, on_delete=models.CASCADE, related_name="topcomply", null=True, )
    created = models.DateTimeField(null=False, blank=False, auto_now_add=True, editable=False, )

    def __str__(self):

armour/templates/legislation/guidance-list.html
{% extends "base-auth.html" %}
{% load crispy_forms_tags static company_tags %}

{% block title %}
   Guidance
{% endblock title %}

{% block pagetitle %}
    Guidance
{% endblock pagetitle %}

{% block breadcrumb %}
{% endblock %}

{% block modal %}
    <!-- Action Modal -->
    <div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content" id="actionModalContent">
             </div>
        </div>
    </div>
{% endblock modal %}

{% block content %}


<div class="card box">
    <h5 class="card-title">Guidance</h5>
    <div class="table-responsive">
        <table class="table">
            <tbody>
                {% for d in docs %}
                <tr>
                    <td>{{ d.title|safe }}</td>
                    <td style="width:100px">{{ d.get_extention }}</td>
                    <td class="text-right">
                        <div class="row-actions">
                            <a target="_blank" href="{{ d.file.url }}" class="btn btn-blank-default btn-sm"><i class="far fa-file-alt mr-1"></i> Download</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

armour/templates/legislation/legislation-topics.html
{% extends "base-auth.html" %}
{% load crispy_forms_tags static company_tags %}

{% block title %}Legislation Register{% endblock %}
{% block pagetitle %}Legislation Register{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'leg-list' %}">Reports</a></li>
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'spec-questions' %}">Register Builder</a></li>
{% endblock %}

{% block modal %}
<!-- Action Modal -->
<div class="modal" id="actionModal" tabindex="-1" role="dialog"></div>
{% endblock modal %}

{% block content %}
<div class="row">
  <!-- Progress -->
  <div class="col-sm-12">
    <div class="progress-wrapper">
      <div class="form-group">
        <label>Select location</label>
        <select class="form-control" name="location" id="id_location" onchange="refreshData();">
          {% for o in data.locations %}
          <option value="{{ o.id|safe }}">{{ o.name|safe }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label>Select topic</label>
        <select class="form-control" name="topic" id="id_topic" onchange="refreshData();">
          {% for o in data.topics %}
          <option value="{{ o.id|safe }}">{{ o.name|safe }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group form-progress">
        <label>Progress<span class="legend-overall">overall</span><span class="legend-product">product</span></label>
        <div class="progress" id="progress-product">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div class="progress" id="progress-overall">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- Pagination  -->
  <div class="col-md-12 col-sm-12">
    <div class="card box mb-2">
      <div class="action-btns w-pagination-top">
        <a href="{% url 'spec-questions' %}" class="btn btn-blank"><i class="fas fa-arrow-left mr-3"></i> Register Builder</a>
        <div class="page-pagination pagination-leg">
          <button class="btn btn-blank" type="button" onclick="prevView()" title="Previous Page"><i class="fas fa-chevron-left"></i></button>
          <div class="page-current">
            <input class="form-control curr-tab" type="number" onchange="setView(this);" id="curr-tab" value="1">
            <span class="lg-counter">/ {{ ltopics|length }}</span>
          </div>
          <button class="btn btn-blank" onclick="nextView()" title="Next Page"><i class="fas fa-chevron-right"></i></button>
        </div>
        <a href="{% url 'non-conformance' %}" class="btn btn-primary" title="Finish Legislation Register">Finish <i class="fas fa-arrow-right ml-3"></i></a>
      </div>
    </div>
  </div>

  <!-- Nav -->
  <div class="col-sm-12" id="page-nav-wrapper">
    <div class="card box mb-2">
      <div class="page-status">
        <div class="page-nav">

        </div>
      </div>
    </div>
  </div>

  <!-- Legislation page -->
  <div class="col-md-12 col-sm-12" id ="leg-content"></div>

  <!-- Pagination  -->
  <div class="col-md-12 col-sm-12">
    <div class="card box">
      <div class="action-btns w-pagination">
        <a href="{% url 'spec-questions' %}" class="btn btn-blank btn-lg"><i class="fas fa-arrow-left mr-3"></i> Register Builder</a>
        <div class="page-pagination pagination-leg">
          <button class="btn btn-blank" type="button" onclick="prevView()" title="Previous Page"><i class="fas fa-chevron-left"></i></button>
          <div class="page-current">
            <input class="form-control curr-tab" type="number" onchange="setView(this);" value="1">
            <span class="lg-counter">/ {{ ltopics|length }}</span>
          </div>
          <button class="btn btn-blank" onclick="nextView()" title="Next Page"><i class="fas fa-chevron-right"></i></button>
        </div>
        <a href="{% url 'non-conformance' %}" class="btn btn-primary btn-lg" title="Finish Legislation Register">Finish <i class="fas fa-arrow-right ml-3"></i></a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
  var urls={datacontent:"{% url 'legislation-topics-content' %}",
  dataset:"{% url 'legislation-topics-set' %}",};
</script>
<script src="{% static 'js/legislation-register.js' %}"></script>
{% if messages %}
<script type="text/javascript">
    $(document).ready(function(){
      {% for message in messages %}
          {% if message.tags == 'error' %}
          setTimeout(function(){ handleErrors(); }, 500);
          {% endif %}
      {% endfor %}
    });
</script>
{% endif %}
{% endblock %}

armour/templates/legislation/specific-questions.html
{% extends "base-auth.html" %}
{% load crispy_forms_tags static company_tags %}

{% block title %}Register Builder{% endblock %}

{% block pagetitle %}Register Builder{% endblock pagetitle %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'leg-list' %}">Reports</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <!-- Progress -->
    <div class="col-sm-12">
        <div class="progress-wrapper">
            <div class="form-group">
                <label>Select location</label>
                <select class="form-control" name="location" id="id_location" onchange="showHideQuestions();">
                    {% for o in data.locations %}
                    <option value="{{ o.id|safe }}">{{ o.name|safe }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label>Select topic</label>
                <select class="form-control" name="topic" id="id_topic" onchange="showHideQuestions();">
                    {% for o in data.topics %}
                    <option value="{{ o.id|safe }}">{{ o.name|safe }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group form-progress">
                <label>Progress<span class="legend-overall">overall</span><span class="legend-product">product</span></label>
                <div class="progress" id="progress-product">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div class="progress" id="progress-overall">
                    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Questions -->
    {% if data.questions|length > 0 %}
    <div class="col-md-12 col-sm-12">
        {% for p in data.questions %}
        {% if p.get_questions|length > 0 %}
        <div class="card box questionboxes" id="product-{{ p.location.id|safe }}-{{ p.topic.id|safe }}">
            <h5 class="card-title mt-0">Specific Questions</h5>
            {% for o in p.get_questions %}
            <div class="question-wrapper">
                {% if o.desc %}
                <div class="question w-tooltip" data-toggle="tooltip" title="{{ o.desc|safe }}">
                    {{ o.title|safe }} <i class="fas fa-info-circle"></i>
                </div>
                {% else %}
                <div class="question">
                    {{ o.title|safe }}
                </div>
                {% endif %}
                <div class="form-radio">
                    <input class="form-radio-input" id="question-yes-{{ o.id|safe }}" onclick="selectQuestion({{ o.id|safe }},1)" name="question-{{ o.id|safe }}" type="radio">
                    <label class="form-radio-label" for="question-yes-{{ o.id|safe }}">Yes</label>
                </div>
                <div class="form-radio">
                    <input class="form-radio-input" id="question-no-{{ o.id|safe }}" onclick="selectQuestion({{ o.id|safe }},0)" name="question-{{ o.id|safe }}" type="radio">
                    <label class="form-radio-label" for="question-no-{{ o.id|safe }}">No</label>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    <div class="col-md-12 col-sm-12">
        <div class="card box">
            <div class="action-btns">
                <a href="{% url 'organization-update' %}" class="btn btn-blank btn-lg float-left"><i class="far fa-edit mr-3"></i> Organisation Details</a>
                <a href="{% url 'spec-questions-confirmation' %}" class="btn btn-primary btn-lg"><i class="fas fa-check mr-3"></i> Generate</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block modal %}
<!-- Action Modal -->
<div class="modal" id="actionModal" tabindex="-1" role="dialog"></div>
<div class="modal fade" id="loadingModal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <i class="fas fa-cog fa-spin"></i>
                Please wait ... We are building your register.
            </div>
        </div>
    </div>
</div>
{% endblock modal %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
    var urls={setquestion:"{% url 'spec-question-set' %}",};
    $(document).ready(function() {
        {% for o in selected %}
            {% if o.response %}
                $('#question-yes-{{ o.question.id|safe }}').prop('checked', true);
            {% else %}
                $('#question-no-{{ o.question.id|safe }}').prop('checked', true);
            {% endif %}
        {% endfor %}
    });
</script>
<script src="{% static 'js/spec-questions.js' %}"></script>
{% if messages %}
<script type="text/javascript">
    $(document).ready(function(){
      {% for message in messages %}
          {% if message.tags == 'error' %}
          handleErrors();
          {% endif %}
      {% endfor %}
    });
</script>
{% endif %}
{% endblock %}